import React from 'react'
import sss1 from '../images/ssss1.png'
import sss2 from '../images/ssss2.png'
import sss3 from '../images/sss3.png'
import './testimonial.css'

function Testimonial() {
  return (
    <div className='testimonial-cover'>
      <div className='testimonial-content'>
        <div className='content11'>
          <img src={sss1} alt=""/>
          <p className='heading'>Search</p>
          <p>Simply add a keyword or a term related to your business in the slogan maker search box.wait for the maggic to happen </p>
        </div>
        <div className='content11'>
          <img src={sss2} alt=""/>
          <p className='heading'>Select</p>
          <p>Choose from thousands of options generated by the slogan maker that fit your needs.</p>
        </div>
        <div className='content11'>
          <img src={sss3} alt=""/>
          <p className='heading'>Stand out</p>
          <p>Congrats on your new slogan. It's time to win the world!</p>
        </div>
      </div>
     </div>
        
      
   
  )
}

export default Testimonial
